repos:
  - repo: local
    hooks:
      - id: trunk-fmt
        name: Run trunk fmt
        entry: trunk fmt
        language: system
        always_run: true

      - id: terraform-validate
        name: Terraform validate
        entry: bash -c "cd terraform && terraform validate"
        language: system
        pass_filenames: false
