[project]
name = "infra"
version = "0.1.0"
description = "Repository containing the infrastructure-as-code (IaC) for my personal stack."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.2.0",
    "pyinfra>=3.3.1",
    "pyyaml>=6.0.2",
]
