services:
  drive:
    port: 5068
    host_header: upstream
  id:
    port: 3232
    host_header: domain
  karakeep:
    port: 3000
    host_header: domain
  paperless:
    port: 8010
    host_header: domain
  photos:
    port: 2283
    host_header: domain
