services:
  drive:
    port: 5068
    host_header: upstream
    public: false
  homarr:
    port: 7575
    host_header: domain
    public: false
  id:
    port: 3232
    host_header: domain
    public: true
  karakeep:
    port: 3000
    host_header: domain
    public: true
  paperless:
    port: 8010
    host_header: domain
    public: false
  photos:
    port: 2283
    host_header: domain
    public: true
  portainer:
    port: 9696
    host_header: domain
    public: false
